public class Main {
    public static void main(String[] args) {
        String input = "L 4\n" +
                "D 6\n" +
                "R 7\n" +
                "D 9\n" +
                "L 4\n" +
                "R 3\n" +
                "L 8\n" +
                "U 9\n" +
                "D 2\n" +
                "L 3\n" +
                "R 8\n" +
                "L 6\n" +
                "R 6\n" +
                "D 3\n" +
                "U 3\n" +
                "D 2\n" +
                "D 9\n" +
                "D 8\n" +
                "L 2\n" +
                "D 7\n" +
                "U 8\n" +
                "D 5\n" +
                "U 8\n" +
                "R 1\n" +
                "U 8\n" +
                "L 1\n" +
                "L 7\n" +
                "L 6\n" +
                "D 2\n" +
                "L 4\n" +
                "L 4\n" +
                "L 9\n" +
                "D 3\n" +
                "R 8\n" +
                "U 2\n" +
                "U 1\n" +
                "L 2\n" +
                "U 7\n" +
                "R 6\n" +
                "U 4\n" +
                "U 2\n" +
                "U 7\n" +
                "L 4\n" +
                "D 3\n" +
                "L 4\n" +
                "D 5\n" +
                "D 8\n" +
                "U 9\n" +
                "U 4\n" +
                "R 2\n" +
                "U 2\n" +
                "D 1\n" +
                "U 1\n" +
                "U 5\n" +
                "D 3\n" +
                "U 7\n" +
                "L 9\n" +
                "L 9\n" +
                "U 6\n" +
                "D 6\n" +
                "D 8\n" +
                "D 1\n" +
                "L 5\n" +
                "R 3\n" +
                "R 2\n" +
                "R 1\n" +
                "U 8\n" +
                "D 2\n" +
                "D 6\n" +
                "L 9\n" +
                "L 6\n" +
                "U 2\n" +
                "U 1\n" +
                "D 9\n" +
                "R 2\n" +
                "R 7\n" +
                "L 3\n" +
                "R 7\n" +
                "L 6\n" +
                "L 1\n" +
                "R 5\n" +
                "L 2\n" +
                "D 3\n" +
                "D 4\n" +
                "R 2\n" +
                "L 4\n" +
                "U 4\n" +
                "R 1\n" +
                "R 3\n" +
                "L 9\n" +
                "L 8\n" +
                "D 5\n" +
                "R 2\n" +
                "D 3\n" +
                "U 9\n" +
                "U 1\n" +
                "D 3\n" +
                "D 2\n" +
                "U 1\n" +
                "L 5\n" +
                "U 9\n" +
                "D 3\n" +
                "D 5\n" +
                "U 5\n" +
                "L 2\n" +
                "U 4\n" +
                "L 3\n" +
                "R 5\n" +
                "U 2\n" +
                "D 5\n" +
                "U 3\n" +
                "U 9\n" +
                "R 1\n" +
                "D 6\n" +
                "D 5\n" +
                "L 3\n" +
                "U 5\n" +
                "L 5\n" +
                "L 2\n" +
                "D 3\n" +
                "R 1\n" +
                "D 3\n" +
                "R 5\n" +
                "D 4\n" +
                "D 9\n" +
                "U 8\n" +
                "D 4\n" +
                "D 4\n" +
                "D 9\n" +
                "D 3\n" +
                "R 1\n" +
                "U 5\n" +
                "U 7\n" +
                "D 7\n" +
                "U 1\n" +
                "D 2\n" +
                "L 5\n" +
                "U 8\n" +
                "L 1\n" +
                "D 8\n" +
                "L 2\n" +
                "D 7\n" +
                "U 3\n" +
                "D 4\n" +
                "D 3\n" +
                "R 4\n" +
                "L 5\n" +
                "L 2\n" +
                "U 6\n" +
                "L 8\n" +
                "L 2\n" +
                "D 2\n" +
                "D 5\n" +
                "R 8\n" +
                "U 7\n" +
                "L 5\n" +
                "D 7\n" +
                "L 5\n" +
                "R 1\n" +
                "L 3\n" +
                "L 7\n" +
                "L 6\n" +
                "L 8\n" +
                "R 1\n" +
                "D 1\n" +
                "R 1\n" +
                "D 5\n" +
                "R 4\n" +
                "R 3\n" +
                "R 9\n" +
                "U 4\n" +
                "L 5\n" +
                "L 6\n" +
                "R 8\n" +
                "U 9\n" +
                "L 3\n" +
                "U 3\n" +
                "R 2\n" +
                "L 5\n" +
                "D 6\n" +
                "R 9\n" +
                "U 5\n" +
                "D 9\n" +
                "L 6\n" +
                "U 2\n" +
                "U 4\n" +
                "L 1\n" +
                "D 4\n" +
                "U 8\n" +
                "U 8\n" +
                "U 3\n" +
                "U 4\n" +
                "U 4\n" +
                "R 7\n" +
                "R 8\n" +
                "R 9\n" +
                "D 6\n" +
                "D 3\n" +
                "D 2\n" +
                "D 7\n" +
                "U 5\n" +
                "L 4\n" +
                "R 6\n" +
                "L 5\n" +
                "L 9\n" +
                "D 9\n" +
                "U 2\n" +
                "D 9\n" +
                "R 3\n" +
                "U 9\n" +
                "D 3\n" +
                "D 3\n" +
                "U 5\n" +
                "L 2\n" +
                "L 8\n" +
                "U 8\n" +
                "R 2\n" +
                "D 8\n" +
                "R 1\n" +
                "U 7\n" +
                "L 4\n" +
                "L 9\n" +
                "D 1\n" +
                "U 4\n" +
                "U 1\n" +
                "R 8\n" +
                "U 2\n" +
                "L 4\n" +
                "D 8\n" +
                "R 6\n" +
                "R 9\n" +
                "R 6\n" +
                "R 6\n" +
                "D 3\n" +
                "D 9\n" +
                "L 6\n" +
                "U 9\n" +
                "D 5\n" +
                "L 7\n" +
                "D 4\n" +
                "L 6\n" +
                "U 8\n" +
                "L 6\n" +
                "D 3\n" +
                "D 5\n" +
                "R 5\n" +
                "U 9\n" +
                "L 3\n" +
                "U 7\n" +
                "D 9\n" +
                "L 2\n" +
                "D 6\n" +
                "D 7\n" +
                "L 7\n" +
                "L 5\n" +
                "U 3\n" +
                "L 1\n" +
                "D 9\n" +
                "U 6\n" +
                "U 4\n" +
                "U 5\n" +
                "R 8\n" +
                "R 4\n" +
                "R 3\n" +
                "D 8\n" +
                "L 1\n" +
                "U 5\n" +
                "U 1\n" +
                "L 9\n" +
                "L 9\n" +
                "R 4\n" +
                "L 1\n" +
                "U 5\n" +
                "L 6\n" +
                "D 9\n" +
                "L 8\n" +
                "U 4\n" +
                "L 3\n" +
                "R 9\n" +
                "R 9\n" +
                "R 4\n" +
                "L 3\n" +
                "U 1\n" +
                "L 2\n" +
                "D 2\n" +
                "U 4\n" +
                "D 2\n" +
                "D 1\n" +
                "R 7\n" +
                "U 2\n" +
                "L 8\n" +
                "U 6\n" +
                "U 4\n" +
                "L 1\n" +
                "R 8\n" +
                "D 7\n" +
                "L 2\n" +
                "D 8\n" +
                "L 9\n" +
                "U 2\n" +
                "R 6\n" +
                "L 4\n" +
                "U 3\n" +
                "L 1\n" +
                "L 3\n" +
                "L 6\n" +
                "D 1\n" +
                "L 2\n" +
                "U 8\n" +
                "L 9\n" +
                "L 3\n" +
                "R 3\n" +
                "R 6\n" +
                "U 2\n" +
                "R 4\n" +
                "R 3\n" +
                "R 4\n" +
                "D 5\n" +
                "L 4\n" +
                "D 3\n" +
                "L 1\n" +
                "R 7\n" +
                "L 8\n" +
                "R 3\n" +
                "L 3\n" +
                "D 5\n" +
                "D 9\n" +
                "R 3\n" +
                "R 9\n" +
                "U 8\n" +
                "U 4\n" +
                "D 2\n" +
                "L 7\n" +
                "D 2\n" +
                "D 3\n" +
                "R 6\n" +
                "U 1\n" +
                "D 4\n" +
                "U 5\n" +
                "L 7\n" +
                "L 7\n" +
                "R 6\n" +
                "L 5\n" +
                "L 9\n" +
                "U 9\n" +
                "D 2\n" +
                "U 4\n" +
                "U 1\n" +
                "D 1\n" +
                "D 4\n" +
                "D 2\n" +
                "R 9\n" +
                "D 1\n" +
                "U 1\n" +
                "U 6\n" +
                "U 2\n" +
                "R 9\n" +
                "R 8\n" +
                "L 3\n" +
                "L 4\n" +
                "U 3\n" +
                "D 6\n" +
                "R 2\n" +
                "U 7\n" +
                "D 4\n" +
                "D 3\n" +
                "R 9\n" +
                "U 3\n" +
                "D 9\n" +
                "L 7\n" +
                "R 4\n" +
                "U 1\n" +
                "R 1\n" +
                "D 6\n" +
                "U 9\n" +
                "L 4\n" +
                "R 1\n" +
                "D 1\n" +
                "L 4\n" +
                "L 8\n" +
                "R 2\n" +
                "L 8\n" +
                "R 5\n" +
                "U 8\n" +
                "U 8\n" +
                "L 2\n" +
                "R 9\n" +
                "L 4\n" +
                "R 3\n" +
                "R 9\n" +
                "D 1\n" +
                "R 4\n" +
                "L 8\n" +
                "U 2\n" +
                "R 1\n" +
                "R 9\n" +
                "D 8\n" +
                "D 3\n" +
                "R 7\n" +
                "L 3\n" +
                "R 9\n" +
                "D 8\n" +
                "R 7\n" +
                "L 9\n" +
                "U 6\n" +
                "U 1\n" +
                "D 3\n" +
                "D 4\n" +
                "U 3\n" +
                "D 2\n" +
                "D 7\n" +
                "D 2\n" +
                "R 4\n" +
                "L 1\n" +
                "U 5\n" +
                "R 2\n" +
                "L 3\n" +
                "R 1\n" +
                "L 9\n" +
                "D 8\n" +
                "L 7\n" +
                "L 2\n" +
                "L 8\n" +
                "R 1\n" +
                "R 4\n" +
                "R 6\n" +
                "R 9\n" +
                "D 5\n" +
                "L 9\n" +
                "D 7\n" +
                "R 7\n" +
                "L 7\n" +
                "U 7\n" +
                "D 7\n" +
                "L 8\n" +
                "R 1\n" +
                "L 6\n" +
                "R 8\n" +
                "L 5\n" +
                "D 3\n" +
                "U 5\n" +
                "L 9\n" +
                "D 6\n" +
                "U 5\n" +
                "D 3\n" +
                "D 8\n" +
                "U 2\n" +
                "D 2\n" +
                "R 2\n" +
                "U 3\n" +
                "D 2\n" +
                "R 5\n" +
                "R 8\n" +
                "U 9\n" +
                "D 3\n" +
                "L 6\n" +
                "R 8\n" +
                "D 6\n" +
                "D 1\n" +
                "R 7\n" +
                "L 2\n" +
                "R 7\n" +
                "R 7\n" +
                "U 6\n" +
                "U 8\n" +
                "L 9\n" +
                "L 1\n" +
                "U 9\n" +
                "U 7\n" +
                "L 4\n" +
                "D 3\n" +
                "R 2\n" +
                "D 7\n" +
                "D 5\n" +
                "R 6\n" +
                "D 9\n" +
                "D 8\n" +
                "R 9\n" +
                "R 8\n" +
                "U 4\n" +
                "U 5\n" +
                "L 1\n" +
                "U 5\n" +
                "R 9\n" +
                "D 6\n" +
                "R 5\n" +
                "U 3\n" +
                "D 6\n" +
                "U 4\n" +
                "U 4\n" +
                "L 8\n" +
                "U 9\n" +
                "R 6\n" +
                "R 2\n" +
                "L 4\n" +
                "D 8\n" +
                "L 3\n" +
                "U 3\n" +
                "U 2\n" +
                "L 9\n" +
                "U 1\n";
        String[] ichBinEinGamer = input.split("\n");
        for (int i = 0; i < ichBinEinGamer.length; i++) {

            move(ichBinEinGamer[i].charAt(0), Character.getNumericValue(ichBinEinGamer[i].charAt(2)));
        }
        System.out.println(x + "," + y);

    }

    static int x = 0;
    static int y = 0;

    private static void move(char direction, int pocet) {

        for (int i = 0; i < pocet; i++) {


            switch (direction) {
                case 'U':
                    y += 1;
                    break;
                case 'D':
                    y -= 1;
                    break;
                case 'R':
                    x += 1;
                    break;
                case 'L':
                    x -= 1;
                    break;
            }
        }
    }
}
